debug: false
server:
  port: 8088

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orders
      username: mongoadmin
      password: TfQM*r8Ak7@Ghd4>EL?C9q

  rabbitmq:
    host: localhost
    port: 5672

messaging:
  queue:
    order:
      create: q.order-create
      cancel: q.order-cancel

